# Generated by Django 3.0.1 on 2020-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_leitura', models.IntegerField(choices=[(0, 'Ensolarado'), (1, 'Chuvoso'), (3, 'Nublado'), (4, 'Neve')], default=0)),
                ('temperatura', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
